// Day registry + date mapping for ru-catfishing.
// Day 0 = 2026-06-04 (the original day1, shifted to "yesterday").
// Day 1 = 2026-06-05 (the new set), and so on, one puzzle-day per calendar day.
// NOTE: import block + DAYS map are generated by scripts/gen_index.py.
import dayM1 from './day-1.json';
import day0 from './day0.json';
import day1 from './day1.json';
import day2 from './day2.json';
import day3 from './day3.json';
import day4 from './day4.json';
import day5 from './day5.json';
import day6 from './day6.json';
import day7 from './day7.json';
import day8 from './day8.json';
import day9 from './day9.json';
import day10 from './day10.json';
import day11 from './day11.json';
import day12 from './day12.json';
import day13 from './day13.json';
import day14 from './day14.json';
import day15 from './day15.json';
import day16 from './day16.json';
import day17 from './day17.json';
import day18 from './day18.json';
import day19 from './day19.json';
import day20 from './day20.json';
import day21 from './day21.json';
import day22 from './day22.json';
import day23 from './day23.json';
import day24 from './day24.json';
import day25 from './day25.json';
import day26 from './day26.json';
import day27 from './day27.json';
import day28 from './day28.json';
import day29 from './day29.json';
import day30 from './day30.json';
import day31 from './day31.json';
import day32 from './day32.json';
import day33 from './day33.json';
import day34 from './day34.json';
import day35 from './day35.json';
import day36 from './day36.json';
import day37 from './day37.json';
import day38 from './day38.json';
import day39 from './day39.json';
import day40 from './day40.json';
import day41 from './day41.json';
import day42 from './day42.json';
import day43 from './day43.json';
import day44 from './day44.json';
import day45 from './day45.json';
import day46 from './day46.json';
import day47 from './day47.json';
import day48 from './day48.json';
import day49 from './day49.json';
import day50 from './day50.json';
import day51 from './day51.json';
import day52 from './day52.json';
import day53 from './day53.json';
import day54 from './day54.json';
import day55 from './day55.json';
import day56 from './day56.json';
import day57 from './day57.json';
import day58 from './day58.json';
import day59 from './day59.json';
import day60 from './day60.json';
import day61 from './day61.json';
import day62 from './day62.json';
import day63 from './day63.json';
import day64 from './day64.json';
import day65 from './day65.json';
import day66 from './day66.json';
import day67 from './day67.json';
import day68 from './day68.json';
import day69 from './day69.json';
import day70 from './day70.json';
import day71 from './day71.json';
import day72 from './day72.json';
import day73 from './day73.json';
import day74 from './day74.json';
import day75 from './day75.json';
import day76 from './day76.json';
import day77 from './day77.json';
import day78 from './day78.json';
import day79 from './day79.json';
import day80 from './day80.json';
import day81 from './day81.json';
import day82 from './day82.json';
import day83 from './day83.json';
import day84 from './day84.json';
import day85 from './day85.json';
import day86 from './day86.json';
import day87 from './day87.json';
import day88 from './day88.json';
import day89 from './day89.json';
import day90 from './day90.json';
import day91 from './day91.json';
import day92 from './day92.json';
import day93 from './day93.json';
import day94 from './day94.json';
import day95 from './day95.json';
import day96 from './day96.json';
import day97 from './day97.json';
import day98 from './day98.json';
import day99 from './day99.json';
import day100 from './day100.json';
import day101 from './day101.json';
import day102 from './day102.json';
import day103 from './day103.json';
import day104 from './day104.json';
import day105 from './day105.json';
import day106 from './day106.json';
import day107 from './day107.json';
import day108 from './day108.json';
import day109 from './day109.json';

// index -> strict day json. Regenerated by gen_index.py.
export const DAYS = {
  '-1': dayM1, 0: day0, 1: day1, 2: day2, 3: day3, 4: day4, 5: day5, 6: day6, 7: day7,
  8: day8, 9: day9, 10: day10, 11: day11, 12: day12, 13: day13, 14: day14, 15: day15,
  16: day16, 17: day17, 18: day18, 19: day19, 20: day20, 21: day21, 22: day22, 23: day23,
  24: day24, 25: day25, 26: day26, 27: day27, 28: day28, 29: day29, 30: day30, 31: day31,
  32: day32, 33: day33, 34: day34, 35: day35, 36: day36, 37: day37, 38: day38, 39: day39,
  40: day40, 41: day41, 42: day42, 43: day43, 44: day44, 45: day45, 46: day46, 47: day47,
  48: day48, 49: day49, 50: day50, 51: day51, 52: day52, 53: day53, 54: day54, 55: day55,
  56: day56, 57: day57, 58: day58, 59: day59, 60: day60, 61: day61, 62: day62, 63: day63,
  64: day64, 65: day65, 66: day66, 67: day67, 68: day68, 69: day69, 70: day70, 71: day71,
  72: day72, 73: day73, 74: day74, 75: day75, 76: day76, 77: day77, 78: day78, 79: day79,
  80: day80, 81: day81, 82: day82, 83: day83, 84: day84, 85: day85, 86: day86, 87: day87,
  88: day88, 89: day89, 90: day90, 91: day91, 92: day92, 93: day93, 94: day94, 95: day95,
  96: day96, 97: day97, 98: day98, 99: day99, 100: day100, 101: day101, 102: day102,
  103: day103, 104: day104, 105: day105, 106: day106, 107: day107, 108: day108,
  109: day109,
};

// Calendar anchor: day 0 falls on this local date.
const BASE = new Date(2026, 5, 4); // months are 0-based -> June 4, 2026
const MS_PER_DAY = 86400000;

function atMidnight(d) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime();
}

// Which day index does "today" (the user's local date) correspond to?
export function todayIndex(now = new Date()) {
  return Math.round((atMidnight(now) - atMidnight(BASE)) / MS_PER_DAY);
}

// The calendar Date for a given day index.
export function dateForDay(n) {
  return new Date(atMidnight(BASE) + n * MS_PER_DAY);
}

// Highest day index that actually has data built (the end of the buffer).
export function maxDay() {
  return Math.max(...Object.keys(DAYS).map(Number));
}

const MONTHS = [
  'января', 'февраля', 'марта', 'апреля', 'мая', 'июня',
  'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря',
];

export function fmtDate(n) {
  const d = dateForDay(n);
  return `${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()}`;
}

// Day indexes that actually exist AND whose date has arrived (no spoilers from
// future days), newest first. When `unlocked` (author mode) is true, ALL built
// days are returned — including future ones — so you can play ahead.
export function availableDays(now = new Date(), unlocked = false) {
  const ceil = unlocked ? maxDay() : todayIndex(now);
  return Object.keys(DAYS)
    .map(Number)
    .filter((n) => n <= ceil)
    .sort((a, b) => b - a);
}

// The day to show by default: the latest available one (today, or the most
// recent built day if today's isn't built yet).
export function currentDay(now = new Date()) {
  const avail = availableDays(now);
  return avail.length ? avail[0] : 0;
}

// Resolve a requested ?day=N to a valid, available index (else the current day).
// NOTE: when there is no ?day param, `requested` is null/'' -> must fall back to
// the current day. (Number(null) === 0, so we can't let it reach the parse path,
// or every default visit would land on day 0.)
export function resolveDay(requested, now = new Date(), unlocked = false) {
  if (requested === null || requested === undefined || requested === '') {
    return currentDay(now);
  }
  const n = Number(requested);
  const ceil = unlocked ? maxDay() : todayIndex(now);
  if (Number.isInteger(n) && DAYS[n] && n <= ceil) return n;
  return currentDay(now);
}
