#!/usr/bin/env python3
"""Regenerate the import block + DAYS map in app/src/lib/days/index.js.

Scans every day*.json present and rebuilds the top of index.js (imports + the
DAYS object). Everything from the "// Calendar anchor" line onward (the date
logic) is preserved verbatim, so this only touches the registry.
"""
import os
import re
import glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DAYS_DIR = os.path.join(ROOT, "app", "src", "lib", "days")
INDEX = os.path.join(DAYS_DIR, "index.js")


def varname(n):
    return f"dayM{abs(n)}" if n < 0 else f"day{n}"


def main():
    idxs = []
    for f in glob.glob(os.path.join(DAYS_DIR, "day*.json")):
        m = re.match(r"day(-?\d+)\.json$", os.path.basename(f))
        if m:
            idxs.append(int(m.group(1)))
    idxs = sorted(set(idxs))

    imports = [
        "// Day registry + date mapping for ru-catfishing.",
        "// Day 0 = 2026-06-04 (the original day1, shifted to \"yesterday\").",
        "// Day 1 = 2026-06-05 (the new set), and so on, one puzzle-day per calendar day.",
        "// NOTE: import block + DAYS map are generated by scripts/gen_index.py.",
    ]
    for n in idxs:
        imports.append(f"import {varname(n)} from './day{n}.json';")

    entries = ", ".join(f"'{n}': {varname(n)}" if n < 0 else f"{n}: {varname(n)}"
                        for n in idxs)
    days_block = [
        "",
        "// index -> strict day json. Regenerated by gen_index.py.",
        "export const DAYS = {",
    ]
    # wrap entries ~6 per line for readability
    parts = [f"'{n}': {varname(n)}" if n < 0 else f"{n}: {varname(n)}" for n in idxs]
    line = "  "
    for p in parts:
        if len(line) + len(p) + 2 > 92:
            days_block.append(line.rstrip())
            line = "  "
        line += p + ", "
    if line.strip():
        days_block.append(line.rstrip())
    days_block.append("};")
    days_block.append("")

    old = open(INDEX, encoding="utf-8").read()
    anchor = old.index("// Calendar anchor:")
    tail = old[anchor:]

    new = "\n".join(imports) + "\n" + "\n".join(days_block) + "\n" + tail
    open(INDEX, "w", encoding="utf-8").write(new)
    print(f"wrote index.js with {len(idxs)} days: "
          f"{idxs[0]}..{idxs[-1]} ({len(idxs)} total)")


if __name__ == "__main__":
    main()
